import { Article } from "@/types";

export const articles: Article[] = [
  {
    id: "a1",
    title: "T1 Dominates VCT Champions 2026 Opening Day",
    excerpt: "T1 showed incredible form defeating Fnatic 13-5 in the first match of the tournament.",
    content: "Full article content here...",
    thumbnail: "/mock/articles/t1-vct2026.svg",
    category: "recap",
    author: "Alex Chen",
    publishDate: new Date(Date.now() - 7200000).toISOString(),
    readTime: 4,
    tags: ["T1", "VCT", "Valorant"],
  },
  {
    id: "a2",
    title: "Paper Rex's f0rsakeN: 'We're here to win, not to participate'",
    excerpt: "Exclusive interview with PRX's star duelist before the VCT Champions 2026 semifinal.",
    content: "Full article content here...",
    thumbnail: "/mock/articles/forsaken-interview.svg",
    category: "interview",
    author: "Sarah Kim",
    publishDate: new Date(Date.now() - 86400000).toISOString(),
    readTime: 6,
    tags: ["PRX", "Interview", "Valorant"],
  },
  {
    id: "a3",
    title: "ESL Pro League Season 21 Full Schedule Revealed",
    excerpt: "Twenty-four teams will compete across six weeks starting March 1st.",
    content: "Full article content here...",
    thumbnail: "/mock/articles/eslpro-s21.svg",
    category: "news",
    author: "Marcus Johnson",
    publishDate: new Date(Date.now() - 172800000).toISOString(),
    readTime: 3,
    tags: ["ESL", "CS2", "Announcement"],
  },
  {
    id: "a4",
    title: "Top 5 Plays from VCT Champions 2026 Day 1",
    excerpt: "From a 1v4 clutch to an ace in overtime — here are the highlights.",
    content: "Full article content here...",
    thumbnail: "/mock/articles/highlights-day1.svg",
    category: "highlight",
    author: "Lisa Park",
    publishDate: new Date(Date.now() - 3600000).toISOString(),
    readTime: 2,
    tags: ["Highlights", "VCT", "Valorant"],
  },
  {
    id: "a5",
    title: "Sentinels Acquire TenZ Under New Contract Terms",
    excerpt: "TenZ re-signs with Sentinels for two more years in a record-breaking deal.",
    content: "Full article content here...",
    thumbnail: "/mock/articles/tenz-resign.svg",
    category: "news",
    author: "David Torres",
    publishDate: new Date(Date.now() - 259200000).toISOString(),
    readTime: 5,
    tags: ["Sentinels", "TenZ", "Transfer"],
  },
  {
    id: "a6",
    title: "Worlds 2025 Recap: T1 Claims Fifth World Championship",
    excerpt: "A legendary run — T1 goes 18-0 through the entire 2025 World Championship.",
    content: "Full article content here...",
    thumbnail: "/mock/articles/worlds-2025-recap.svg",
    category: "recap",
    author: "Emma Wilson",
    publishDate: "2025-11-03T10:00:00Z",
    readTime: 8,
    tags: ["T1", "Worlds", "LoL"],
  },
];
