import { Team } from "@/types";

export const teams: Team[] = [
  {
    id: "t1",
    name: "T1",
    tag: "T1",
    logo: "/mock/teams/t1.svg",
    country: "KR",
    region: "Asia",
    rank: 1,
    wins: 15,
    losses: 2,
    draws: 0,
    points: 100,
    captainId: "p1",
    players: [
      { id: "p1", ign: "Faker", realName: "Lee Sang-hyeok", role: "Mid", avatar: "/mock/players/faker.svg", country: "KR" },
      { id: "p2", ign: "Gumayusi", realName: "Lee Min-hyeong", role: "Bot", avatar: "/mock/players/gumayusi.svg", country: "KR" },
      { id: "p3", ign: "Keria", realName: "Ryu Min-seok", role: "Support", avatar: "/mock/players/keria.svg", country: "KR" },
      { id: "p4", ign: "Zeus", realName: "Choi Woo-je", role: "Top", avatar: "/mock/players/zeus.svg", country: "KR" },
      { id: "p5", ign: "Oner", realName: "Moon Hyeon-jun", role: "Jungle", avatar: "/mock/players/oner.svg", country: "KR" },
    ],
  },
  {
    id: "fnc",
    name: "Fnatic",
    tag: "FNC",
    logo: "/mock/teams/fnc.svg",
    country: "EU",
    region: "Europe",
    rank: 2,
    wins: 12,
    losses: 4,
    draws: 1,
    points: 85,
    captainId: "p6",
    players: [
      { id: "p6", ign: "Upset", realName: "Elias Lipp", role: "Bot", avatar: "/mock/players/upset.svg", country: "DE" },
      { id: "p7", ign: "Humanoid", realName: "Martin Sundelin", role: "Mid", avatar: "/mock/players/humanoid.svg", country: "SE" },
      { id: "p8", ign: "Razork", realName: "Ivan Martin", role: "Jungle", avatar: "/mock/players/razork.svg", country: "ES" },
      { id: "p9", ign: "Wunder", realName: "Martin Hansen", role: "Top", avatar: "/mock/players/wunder.svg", country: "DK" },
      { id: "p10", ign: "Rhukz", realName: "Daniel Bjerre", role: "Support", avatar: "/mock/players/rhukz.svg", country: "DK" },
    ],
  },
  {
    id: "prx",
    name: "Paper Rex",
    tag: "PRX",
    logo: "/mock/teams/prx.svg",
    country: "SG",
    region: "SEA",
    rank: 3,
    wins: 11,
    losses: 5,
    draws: 0,
    points: 78,
    captainId: "p11",
    players: [
      { id: "p11", ign: "f0rsakeN", realName: "Jason Susanto", role: "Duelist", avatar: "/mock/players/forsaken.svg", country: "SG" },
      { id: "p12", ign: "mindfreak", realName: "Aaron Leonhart", role: "Controller", avatar: "/mock/players/mindfreak.svg", country: "AU" },
      { id: "p13", ign: "Jinggg", realName: "Wang Jing Jie", role: "Duelist", avatar: "/mock/players/jinggg.svg", country: "SG" },
      { id: "p14", ign: "d4v41", realName: "Khalish Rusyaidee", role: "Initiator", avatar: "/mock/players/d4v41.svg", country: "MY" },
      { id: "p15", ign: "something", realName: "Ilya Petrov", role: "Sentinel", avatar: "/mock/players/something.svg", country: "RU" },
    ],
  },
  {
    id: "sen",
    name: "Sentinels",
    tag: "SEN",
    logo: "/mock/teams/sen.svg",
    country: "US",
    region: "Americas",
    rank: 4,
    wins: 10,
    losses: 5,
    draws: 0,
    points: 72,
    captainId: "p16",
    players: [
      { id: "p16", ign: "TenZ", realName: "Tyson Ngo", role: "Duelist", avatar: "/mock/players/tenz.svg", country: "CA" },
      { id: "p17", ign: "Zellsis", realName: "Jordan Montemurro", role: "Duelist", avatar: "/mock/players/zellsis.svg", country: "US" },
      { id: "p18", ign: "Sacy", realName: "Gustavo Rossi", role: "Initiator", avatar: "/mock/players/sacy.svg", country: "BR" },
      { id: "p19", ign: "pANcada", realName: "Bryan Luna", role: "Controller", avatar: "/mock/players/pancada.svg", country: "BR" },
      { id: "p20", ign: "johnqt", realName: "John Marlin", role: "Sentinel", avatar: "/mock/players/johnqt.svg", country: "US" },
    ],
  },
  {
    id: "nrg",
    name: "NRG Esports",
    tag: "NRG",
    logo: "/mock/teams/nrg.svg",
    country: "US",
    region: "Americas",
    rank: 5,
    wins: 9,
    losses: 6,
    draws: 1,
    points: 65,
    captainId: "p21",
    players: [
      { id: "p21", ign: "crashies", realName: "Austin Roberts", role: "Initiator", avatar: "/mock/players/crashies.svg", country: "US" },
      { id: "p22", ign: "Victor", realName: "Victor Wong", role: "Duelist", avatar: "/mock/players/victor.svg", country: "US" },
      { id: "p23", ign: "s0m", realName: "Sam Oh", role: "Controller", avatar: "/mock/players/s0m.svg", country: "US" },
      { id: "p24", ign: "FNS", realName: "Pujan Mehta", role: "Controller", avatar: "/mock/players/fns.svg", country: "CA" },
      { id: "p25", ign: "ardiis", realName: "Ardis Svarenieks", role: "Sentinel", avatar: "/mock/players/ardiis.svg", country: "LV" },
    ],
  },
  {
    id: "tl",
    name: "Team Liquid",
    tag: "TL",
    logo: "/mock/teams/tl.svg",
    country: "EU",
    region: "Europe",
    rank: 6,
    wins: 8,
    losses: 6,
    draws: 2,
    points: 60,
    captainId: "p26",
    players: [
      { id: "p26", ign: "Jamppi", realName: "Elias Olkkonen", role: "Duelist", avatar: "/mock/players/jamppi.svg", country: "FI" },
      { id: "p27", ign: "nAts", realName: "Ayaz Akhmetshin", role: "Sentinel", avatar: "/mock/players/nats.svg", country: "RU" },
      { id: "p28", ign: "Redgar", realName: "Igor Vlasov", role: "Initiator", avatar: "/mock/players/redgar.svg", country: "RU" },
      { id: "p29", ign: "ANGE1", realName: "Kyrylo Karasov", role: "Controller", avatar: "/mock/players/angel.svg", country: "UA" },
      { id: "p30", ign: "ScreaM", realName: "Adil Benrlitom", role: "Duelist", avatar: "/mock/players/scream.svg", country: "BE" },
    ],
  },
];
